name: build artifact from source

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Go
      uses: actions/setup-go@v2
#      with:
#        go-version: '1.14.0'  

    - name: Install dependencies
      run: |
        go version
        go get -u golang.org/x/lint/golint
        
    - name: Run build
      run: go build . 
      
#    - name: Run vet & lint
#      run: |
#        go vet .
#        golint .

    - run: mkdir artifact
    
    - name: 'Tar files'
      run: tar -cvzf artifact/http-script-runner_${GITHUB_REF##*/}_linux_amd64.tar.gz script-exporter
    
    - name: 'ls'
      run: ls -l
    
    - name: 'show release'
      run: echo ${GITHUB_REF##*/}
      

    - uses: ncipollo/release-action@v1
      with:
        artifacts: "artifact/http-script-runner_${GITHUB_REF##*/}_linux_amd64.tar.gz"

#    - name: 'Upload Artifact'
#      uses: actions/upload-artifact@v2
#      with:
#        name: http-script-runner
#        path: ./artifact/http-script-runner_${GITHUB_REF##*/}_linux_amd64.tar.gz 
      
